services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: todo_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:80"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
