services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=todo_db;Username=postgres;Password=postgres"
      Jwt__Key: "6Mf9BPBVTtprmx7XEIYqdT0Pcr+CKptvPm0Ti7Zf7f4="
      Jwt__Issuer: "todo_api"
      Jwt__Audience: "todo_api_users"
    depends_on:
      - postgres
    ports:
      - "5000:80"
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
